require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SnipsController do

  # This should return the minimal set of attributes required to create a valid
  # Snip. As you add validations to Snip, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SnipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all snips as @snips" do
      snip = Snip.create! valid_attributes
      get :index, {}, valid_session
      assigns(:snips).should eq([snip])
    end
  end

  describe "GET show" do
    it "assigns the requested snip as @snip" do
      snip = Snip.create! valid_attributes
      get :show, {:id => snip.to_param}, valid_session
      assigns(:snip).should eq(snip)
    end
  end

  describe "GET new" do
    it "assigns a new snip as @snip" do
      get :new, {}, valid_session
      assigns(:snip).should be_a_new(Snip)
    end
  end

  describe "GET edit" do
    it "assigns the requested snip as @snip" do
      snip = Snip.create! valid_attributes
      get :edit, {:id => snip.to_param}, valid_session
      assigns(:snip).should eq(snip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Snip" do
        expect {
          post :create, {:snip => valid_attributes}, valid_session
        }.to change(Snip, :count).by(1)
      end

      it "assigns a newly created snip as @snip" do
        post :create, {:snip => valid_attributes}, valid_session
        assigns(:snip).should be_a(Snip)
        assigns(:snip).should be_persisted
      end

      it "redirects to the created snip" do
        post :create, {:snip => valid_attributes}, valid_session
        response.should redirect_to(Snip.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved snip as @snip" do
        # Trigger the behavior that occurs when invalid params are submitted
        Snip.any_instance.stub(:save).and_return(false)
        post :create, {:snip => { "name" => "invalid value" }}, valid_session
        assigns(:snip).should be_a_new(Snip)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Snip.any_instance.stub(:save).and_return(false)
        post :create, {:snip => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested snip" do
        snip = Snip.create! valid_attributes
        # Assuming there are no other snips in the database, this
        # specifies that the Snip created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Snip.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => snip.to_param, :snip => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested snip as @snip" do
        snip = Snip.create! valid_attributes
        put :update, {:id => snip.to_param, :snip => valid_attributes}, valid_session
        assigns(:snip).should eq(snip)
      end

      it "redirects to the snip" do
        snip = Snip.create! valid_attributes
        put :update, {:id => snip.to_param, :snip => valid_attributes}, valid_session
        response.should redirect_to(snip)
      end
    end

    describe "with invalid params" do
      it "assigns the snip as @snip" do
        snip = Snip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Snip.any_instance.stub(:save).and_return(false)
        put :update, {:id => snip.to_param, :snip => { "name" => "invalid value" }}, valid_session
        assigns(:snip).should eq(snip)
      end

      it "re-renders the 'edit' template" do
        snip = Snip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Snip.any_instance.stub(:save).and_return(false)
        put :update, {:id => snip.to_param, :snip => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested snip" do
      snip = Snip.create! valid_attributes
      expect {
        delete :destroy, {:id => snip.to_param}, valid_session
      }.to change(Snip, :count).by(-1)
    end

    it "redirects to the snips list" do
      snip = Snip.create! valid_attributes
      delete :destroy, {:id => snip.to_param}, valid_session
      response.should redirect_to(snips_url)
    end
  end

end
